### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by Sjors** [mareczek/international-phone-number#44]
intlTelInput uses jQuery. I'm not sure how difficult it would be to reimplement the UI bits using AngularJS and/or ui.bootstrap, rather than jQuery.

**Comment by Roundaround** [comment]
Something to keep in mind is this project is a wrapper for intlTellInput, not a port.  What you're talking about is for a project of a much larger scale.

**Comment by Sjors** [comment]
I created a bounty for this. Let's see if that attracts anyone: 
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=15217280)](https://www.bountysource.com/issues/15217280-remove-jquery-dependency?utm_source=15217280&utm_medium=shield&utm_campaign=ISSUE_BADGE)
It could be either a (big?) pull request or a separate project, depending on what makes sense.

**Comment by grimor** [comment]
I'll check on intlTelInput code and see what can be done.

**Comment by Ahimta** [comment]
I've been on this for quite a while (about a week).

I am removing jQuery by directly using the native Javascript DOM and events API.
I still need time to wrap this up and ensure browser compatibility (hopefully in 5-10 days)

I also intend some changes that would make the transition easier for example by running jasmine tests on the browser so it is easier to thoroughly test the plugin.

My repo is still a miss with around 50 commits, I will eventually rebase it against upstream and squash it into a single commit.

You can find my repo here: https://github.com/Ahimta/intl-tel-input

**Comment by Ahimta** [comment]
One thing to note is that my [fork](https://github.com/Ahimta/intl-tel-input) is functional and you can try it by cloning the repo and opening `demo.html` in your browser.

In fact, from the start I've been keeping it functional, so much that almost every commit is working on `Google Chrome` and passing all automated tests. And I intend to keep it that way.

However, as I mentioned before there's still work to be done and hopefully by the end it will work without jQuery and still have the same browser compatibility or better.

In addition, I will make sure that it is merged to the original [repo](https://github.com/Bluefieldscom/intl-tel-input), so that it still has the support of the community.

p.s: I am noticing some performance improvements already by about 20% when running tests.

**Comment by Sjors** [comment]
Hi Abdula,

I'm going to review your code in more detail when I'm back from vacation
(around the 28th); difficult on a small mobile screen.

Can you try to take more advantage of AngularJS features? E.g. rather than
using element.addClass(), use ng-class. Instead of building the view
programatically - as the original code does - try using an HTML template.
That would make it way easier to understand and read too.

Sjors

**Comment by Ahimta** [comment]
[international-phone-number](https://github.com/mareczek/international-phone-number) is simply a wrapper using [intl-tel-input](https://github.com/Bluefieldscom/intl-tel-input).

international-phone-number doesn't depend on jQuery directly.
It depends on intl-tel-input, which in turn depends on jQuery.

As I understand it you want to remove jQuery dependency by using Angular for implementing intl-tel-input.

This has many disadvantages.
It will be much slower (10x slower or even more).

**Comment by Ahimta** [comment]
[international-phone-number](https://github.com/mareczek/international-phone-number) is simply a wrapper using [intl-tel-input](https://github.com/Bluefieldscom/intl-tel-input).

international-phone-number doesn't depend on jQuery directly.
It depends on intl-tel-input, which in turn depends on jQuery.

As I understand it you want to remove jQuery dependency by using Angular for implementing intl-tel-input.

## This has many disadvantages.
- It will be much slower (10x slower or even more).
- It will have less contributors , since Angular is still not as popular as jQuery.
- jQuery is a library, so it is still reasonable for most developers to include it in their project even if they are using Angular, React, etc... However, it is unreasonable to include Angular when you're using almost anything else.
- It will almost be a new independent project, you will be responsible for maintaining it and fixing bugs.
- Finally, 90% of your code will not use Angular anyway.

## What most Javascript libraries strive to do
- Have as little external dependencies as possible.
- Write wrappers for frameworks (e.g: Angular, Ember, React, Backbone).

## Why
- Much more people will be able to use the library.
- More people using the library means more contributors, maintainers, bugfixes, features.

**Comment by Sjors** [comment]
That makes sense. I guess there are two approaches:

1 - Create a whole new AngularJS alternative for intl-tel-input, removing
the need for a wrapper. This adds a maintenance burden as you mentioned. On
the other hand, the most important thing is the library of phone number
regular expressions and a list of flags. The UI could perhaps be reproduced
using ui.bootstrap or ui.select. My project - and many other AngularJS
projects - already depends on ui.bootstrap so it wouldn't be an extra
dependency.

It would be a wrapper around the regex library rather than a wrapper
around intl-tel-input. So it's still in line with the javascript component
philosophy, just a difference in what level the wrapper is at (wrapping the
model, rather than the view).

I'm not immediately worried about performance: it's fast enough at the
moment; we'd have to experiment with that.

2 - Avoid the use of jQuery by using another library or falling back on
more primitive methods. This also creates a maintenance problem, because -
as you said - many people still use jQuery and so they would only
contribute to the jQuery version.

Web Components is an interesting development that could make this easier,
but I don't know if that's possible yet.

**Comment by Sjors** [comment]
With the data layer I mean e.g. these files:
https://github.com/Bluefieldscom/intl-tel-input/blob/master/src/js/data.js
https://github.com/Bluefieldscom/intl-tel-input/blob/master/lib/libphonenumber/src/utils.js
https://github.com/behdad/region-flags
Plus the functions that tie all this data together so that if the user types "1650" it returns "+1 (650)" and "us" (or something like that).

**Comment by Ahimta** [comment]
The real magic of international-phone-number is here: https://github.com/Bluefieldscom/intl-tel-input/blob/master/src/js/intlTelInput.js.ejs

1- I have experience with Angular, jQuery and native Javascript DOM.
And I honestly, think moving all intl-tel-input into the wrapper is a really bad idea.
Angular is a SPA framework. Whatever functionality you want to have directly in Angular, you have to expose from intl-tel-input and then use it in the wrapper.

ui.select and ui,bootstrap are mostly for web applications not Javascript libs.

If you move intl-tel-input into the wrapper, you will basically use Javascript DOM API (which I am working on right now) to remove jQuery dependency, and then copy the whole thing and paste it into the wrapper repo.

So, you will basically have some code copied from another repo instead of depending on it using a package manager. This is both not easy and hard to maintain.

2- If you use native Javascript DOM api (primitive methods), then you can use the lib for almost everything in Javascript including jQuery.
So, even though, the lib is not using jQuery, jQuery users use it and have motivation to contribute to it.

Regardless, if you think otherwise, provide me with some code examples illustrating the end result you want to achieve and I will make the necessary changes.

**Comment by Sjors** [comment]
You can use the approach you are working on. But what I had in mind is this:

I would not move intl-tel-input into the wrapper, instead I would extract
the relevant non-ui bits from intl-tel-input and put it in a new project,
seperate from any (AngularJS / jQuery) UI code:

1 - a purely functional JS library that takes a user input string and
returns a formatted phone numer and country code (maybe a few more
functions)

2 - intl-tel-input would use (1) so it becomes a jQuery wrapper (I don't
know if they would switch to that)

3 - an AngularJS wrapper that uses (1) and ui.select or ui.bootstrap, to
creat a similar UI to (2). Maybe less features and configuration options.

Do you think such a split is a bad idea?

The end result would e.g. be a directive used like this:

>
<phone-number ng-model="theNumber" />

It should show the initial value and country flag on load (and whenever
ng-model changes). It should auto-format when the user types, update the
flag and set ng-model to the correct value.

I also need the default-country and preferred-countries attributes.

Here's where I use it:
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/app/templates/configure-mobile-number.jade#L3-L11

**Comment by Ahimta** [comment]
Apparently, I've misinterpreted your [initial comment](https://github.com/mareczek/international-phone-number/issues/44#issue-76996049).

I thought you wanted to use the same functionality without jQuery as a dependency.
I've been working on removing jQuery dependency from intl-tel-input and eventually making it possible to use both int-tel-input and international-phone-number without the need to include jQuery.

I already invested a lot of time in this and will spend more, since I think it is very much worth it.
int-tel-input and international-phone-number will have more users and contributors.
jQuery is a show stopper for many big players (e.g: The Guardian, HuffingtonPost, Netflix).
Aside from prestige, the lib will have more demand and thus more motivation for improvement.

Regardless, it seems you want to create a small custom library for your particular usecase.
For that, I would suggest:
1- Create a new repo.
2- Add a README illustrating the API you want expose.
3- I will fork the repo, implement the API and issue a pull request.

Initially I thing ui.select could be sufficient, depending on your usecases.
In addition, depending on what you want, may need less of the data layer from intl-tel-input.

One final note, for this to be done in a reasonable time, it has to be:
1- Specific to your usecase (for the most part).
2- Not another intl-tel-input, otherwise just use intl-tel-input.

This way it will be tailored to your needs.

p.s: Since My-Wallet-V3-Frontend depends on My-Wallet-V3, why not use it through npm or bower instead of cloning it?

**Comment by Sjors** [comment]
I clarified what I need at our own repository blockchain/My-Wallet-V3-Frontend#152. I can't move the bounty over, but let's continue the discussion there.

**Comment by citizenbob** [comment]
Are you still working on the non-jQuery version of this?

**Comment by Sjors** [comment]
@bduebel yes indeed, it's here: https://github.com/blockchain/bc-phone-number
